<a href="https://colab.research.google.com/github/1antw/Application-of-AI/blob/main/Class02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import torch.nn as nn

In [9]:
# Binary Cross Entropy
y_hat = torch.tensor([[0.77], [0.2], [0.12], [0.97]])
y = torch.tensor([[1.], [0.], [0.], [1.]])
bce = nn.BCELoss(reduction='none')
loss = bce(y_hat, y)
print(loss)

tensor([[0.2614],
        [0.2231],
        [0.1278],
        [0.0305]])


In [10]:
# Softmax(Multi class)
output = torch.tensor([[1.6, -0.8, 3.7], [0.2, -3.2, -1.6]]) #2x3
softmax = nn.Softmax(dim=1) #dim=0 會是1.6 and 0.2這個維度做, dim=1 [1.6, -0.8, 3.7] and [0.2, -3.2, -1.6]
print(softmax(output))
softmax_test = nn.Softmax(dim=0)
print(softmax_test(output))

tensor([[0.1080, 0.0098, 0.8822],
        [0.8343, 0.0278, 0.1379]])
tensor([[0.8022, 0.9168, 0.9950],
        [0.1978, 0.0832, 0.0050]])
